version: '2'
services:
    ui:
        build:
            context: ../
            dockerfile: Dockerfile.ui
        command: nodemon #run app
        ports:
            - "8100:8100"
        links:
            - db:db
        depends_on:
            - db
            - monitor
        entrypoint: ./wait-for-it.sh db:3306
    db:
        image: mysql
        volumes:
            - /data/database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
    monitor:
        build:
            context: ../monitor/
        command: npm start
        volumes:
            - ../monitor:/monitor
        links:
            - db:db
        depends_on:
            - db
