version: '2'
services:
    ui:
        build:
            context: ../
            dockerfile: Dockerfile.ui
        ports:
            - "8100:8100"
            - "9090:9090"
        links:
            - db:db
        depends_on:
            - db
            - monitor
            - mongo
        command: nodemon
    db:
        image: mysql
        volumes:
            - /data/database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
    monitor:
        build:
            context: ../monitor/
        command: npm start
        # volumes:
        #     - ../monitor:/monitor # for developer
        links:
            - db:db
        depends_on:
            - db
    mongo:
        image: mongo
        ports:
            - "27000:27017"
        volumes:
            - /data/mongo:/data/db
